### ISSUE TITLE
Update to latest version of IntelliJ (2018.3.1)

### ISSUE THREAD

**Issue by pauljarvis** [OurFriendIrony/ansible#16]
Have already changed the ansible role to do this, so might send a PR when I get chance

**Comment by OurFriendIrony** [comment]
Does your solution handle "previously" installed versions. It would install the new version in a slightly different location (because of the version number) and then override the "favourite" on the taskbar, but it wont remove the old instance

Also, as the version is actually a "default" value, you can override with the version you personally want to use in your user_profile without affecting the codebase, as so:
```
intellij_year       : "2018.3"
intellij_subversion : "1"
```
